### Получить все товары 1
GET http://localhost:8080/components

### Получить все товары 2
GET http://localhost:8080/components

### Получить все товары 3
GET http://localhost:8080/components

### Получить все товары 4
GET http://localhost:8080/components

### Получить все товары 5
GET http://localhost:8080/components

### Получить все товары 6 (должно бахнуть)
GET http://localhost:8080/components